name: Hack-Quest-CLI

on:
  push:
    tags:
      - 'v*' # Triggers on tags like v1.0.0
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: true
        type: string
        default: '1.0.0'
      skip_publish:
        description: 'Skip PyPI publish'
        required: false
        type: boolean
        default: false

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Install build dependencies
        run: python -m pip install --upgrade pip build
      
      - name: Validate package structure
        run: |
          echo "Checking package structure..."
          ls -la
          if [ -f "__init__.py" ]; then
            echo "✓ __init__.py exists"
          else
            echo "✗ __init__.py missing - creating it"
            touch __init__.py
          fi
          if [ -f "Main_Hack.py" ]; then
            echo "✓ Main_Hack.py exists"
          else
            echo "✗ Main_Hack.py missing!"
            exit 1
          fi
      
      - name: Build package
        run: python -m build
      
      - name: Verify package contents
        run: |
          echo "Checking built package contents..."
          ls -la dist/
          tar -tzf dist/*.tar.gz | grep -E "(\.py$|__init__)" || true
          echo "Package built successfully!"
      
      - name: Display build info
        run: |
          echo "Manual trigger: ${{ github.event_name == 'workflow_dispatch' }}"
          echo "Requested version: ${{ github.event.inputs.version }}"
          echo "Skip publish: ${{ github.event.inputs.skip_publish }}"
      
      - name: Publish package to PyPI
        if: ${{ github.event.inputs.skip_publish != true }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
